version: '3.8'

services:
  farm-admin:
    build:
      context: https://github.com/swarnes1/farm-admin.git
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - API_KEY=rBoolrmakSG77Ol5CidsnWvmdyvjpzXfppuR0J4e-LYtn2zZLABzIyJVn5TeHpuv
      - ETERNALFARM_AGENT_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNAL_API_URL=https://api.eternalfarm.net
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - farm-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - farm-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSntioi004!"]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 180s

volumes:
  mariadb_data:
    driver: local

networks:
  farm-admin-network:
    driver: bridge 