version: '3.8'

services:
  farm-admin:
    container_name: farm-admin
    build:
      context: https://github.com/swarnes1/farm-admin.git
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - API_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNALFARM_AGENT_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNAL_API_URL=https://api.eternalfarm.net
      - ETERNAL_FARM_KEY=${ETERNAL_FARM_KEY:-}
      - ETERNAL_AUTH_KEY=${ETERNAL_AUTH_KEY:-}
      - PORT=3000
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1358933950210379816/Pdfyxcilip-xI3-q5ILOl9eRCl0nhEICZHZuvbyQm9aARgzI7GuHQExqBj1NNfkScPvV
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - farm-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  mariadb:
    container_name: farm-admin-mariadb
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_config:/config
    networks:
      - farm-admin-network
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSntioi004!"]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 180s

volumes:
  mariadb_config:
    driver: local

networks:
  farm-admin-network:
    driver: bridge 