version: '3.8'

services:
  farm-admin-hybrid:
    container_name: farm-admin-hybrid
    build:
      context: https://swarnes1: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@github.com/swarnes1/farm-admin.git
      dockerfile: Dockerfile.hybrid
      no_cache: false
      pull: true
      args:
        REBUILD_TIMESTAMP: 2025-06-02-ETERNALFARM-TOOLS-AUTOSTART-FINAL
    ports:
      - "3333:3001"  # Changed internal port to 3001
      - "5900:5900"  # VNC for DreamBot
      - "8080:8080"  # noVNC web interface
      - "2222:22"    # SSH access
    environment:
      - NODE_ENV=production
      - PORT=3001  # Set internal port to 3001
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - API_KEY=RZbfSKKe3qCtHVk0ty3H41yJc403rMNzdj73v7ar6Owp5kfQjuLiyaRrOsoe81N5
      - ETERNALFARM_AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - AUTH_AGENT_KEY=P52FE7-I2G19W-C2S4R8-BQZZFP-1FADWV-V3
      - ETERNAL_API_URL=https://api.eternalfarm.net
      - ETERNAL_FARM_KEY=${ETERNAL_FARM_KEY:-}
      - ETERNAL_AUTH_KEY=${ETERNAL_AUTH_KEY:-}
      - DISPLAY=:1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-} # Discord webhook for notifications
      - DREAMBOT_USER=${DREAMBOT_USER:-} # DreamBot login user
      - DREAMBOT_PASS=${DREAMBOT_PASS:-} # DreamBot login password
      - PROXY_HOST=${PROXY_HOST:-} # Proxy host for DreamBot
      - PROXY_PORT=${PROXY_PORT:-} # Proxy port for DreamBot
      - PROXY_USER=${PROXY_USER:-} # Proxy user for DreamBot
      - PROXY_PASS=${PROXY_PASS:-} # Proxy password for DreamBot
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - farm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    container_name: farm-admin-mariadb
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/config
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - farm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSntioi004!"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  farm_data:
  dreambot_data:
  mariadb_data:

networks:
  farm-network:
    driver: bridge 